replicaCount: 2

image:
  repository: 471112818913.dkr.ecr.us-east-1.amazonaws.com/cockroach-python-service
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

db:
  host: cockroachdb-public
  port: 26257
  name: defaultdb
  user: root

service:
  type: ClusterIP
  port: 80
