apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repo-url
      type: string

    - name: revision
      type: string
      default: main

  workspaces:
    - name: output

  steps:
    - name: clone
      image: alpine/git:latest

      script: |
        #!/bin/sh
        set -e

        echo "=================================="
        echo "Cleaning old workspace..."
        echo "=================================="

        rm -rf /workspace/output/source

        echo "=================================="
        echo "Cloning Repository..."
        echo "=================================="

        git clone $(params.repo-url) \
          --branch $(params.revision) \
          /workspace/output/source

        echo "=================================="
        echo "Repository cloned successfully"
        echo "=================================="

        echo "Listing repository..."
        find /workspace/output/source -maxdepth 5

        echo "Looking for Dockerfile..."
        find /workspace/output/source -name Dockerfile
