apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko-build

spec:
  params:
    - name: IMAGE
      type: string

  workspaces:
    - name: source

  volumes:
    - name: docker-config
      secret:
        secretName: docker-config

  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:debug

      script: |
        #!/busybox/sh

        echo "==============================="
        echo "Current Directory"
        echo "==============================="
        pwd

        echo ""
        echo "==============================="
        echo "Workspace Contents"
        echo "==============================="
        find /workspace

        echo ""
        echo "==============================="
        echo "Looking for Dockerfile"
        echo "==============================="
        find /workspace -name Dockerfile

        echo ""
        echo "==============================="
        echo "Building Image"
        echo "==============================="

        /kaniko/executor \
          --dockerfile=/workspace/source/source/eks-platform/tekton/tekton-python-demo/Dockerfile \
          --context=/workspace/source/source/eks-platform/tekton/tekton-python-demo \
          --destination=$(params.IMAGE) \
          --cache=true

      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
