apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko-build

spec:
  params:
    - name: IMAGE
      type: string

  workspaces:
    - name: source

  volumes:
    - name: docker-config
      secret:
        secretName: docker-config
        items:
          - key: .dockerconfigjson
            path: config.json

  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:debug

      workingDir: /workspace/source/source

      command:
        - /kaniko/executor

      args:
        - --dockerfile=eks-platform/tekton/tekton-python-demo/Dockerfile
        - --context=eks-platform/tekton/tekton-python-demo
        - --destination=$(params.IMAGE)
        - --cache=true

      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
