apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroach-python-service
  namespace: cockroach
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockroach-python-service
  template:
    metadata:
      labels:
        app: cockroach-python-service
    spec:
      containers:
        - name: python-app
          image: your-image:latest

          ports:
            - containerPort: 8080

          env:
            - name: DB_HOST
              value: "cockroachdb-public.cockroach.svc.cluster.local"
            - name: DB_PORT
              value: "26257"
            - name: DB_NAME
              value: "defaultdb"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cockroach-python-service-db-secret
                  key: password
