apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cockroach-python-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cockroach-python-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cockroach-python-service.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.db.port | quote }}
